/*
 * APM - Android Package Manager
 *
 * RedHead Industries - Technologies Branch
 * Copyright (C) 2025 RedHead Industries
 *
 * File: export_path.cpp
 * Purpose: Implement helper scripts and profile sourcing so installed commands
 * land on PATH.
 * Last Modified: November 27th, 2025. - 8:01 AM Eastern Time.
 * Author: Matthew DaLuz - RedHead Founder
 *
 * APM is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * APM is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with APM. If not, see <https://www.gnu.org/licenses/>.
 *
 */

#include "export_path.hpp"

#include "config.hpp"
#include "fs.hpp"
#include "logger.hpp"

#include <cerrno>
#include <cstring>
#include <ctime>
#include <fstream>
#include <iostream>
#include <sstream>
#include <string>
#include <sys/stat.h>
#include <sys/wait.h>
#include <unistd.h>
#include <vector>

namespace {

// Create parent directories for a file path if they do not exist.
bool ensureParentDir(const std::string &path) {
  auto pos = path.find_last_of('/');
  if (pos == std::string::npos)
    return true;
  std::string dir = path.substr(0, pos);
  if (dir.empty())
    return true;
  return apm::fs::createDirs(dir);
}

// Write a shell script and ensure it has execute permissions so shells can
// source it directly.
bool writeExecutableScript(const std::string &path,
                           const std::string &content) {
  if (!ensureParentDir(path)) {
    apm::logger::warn("export_path: failed to create parent directory for " +
                      path);
    return false;
  }

  if (!apm::fs::writeFile(path, content)) {
    apm::logger::warn("export_path: failed to write script " + path);
    return false;
  }

  if (::chmod(path.c_str(), 0755) != 0) {
    apm::logger::warn("export_path: chmod failed for " + path + ": " +
                      std::strerror(errno));
  }

  return true;
}

// Emit a helper script that shells can source to prepend package-specific
// command directories to PATH.
bool ensureCommandsPathHelperScript() {
  std::ostringstream script;
  script << "#!/system/bin/sh\n";
  script
      << "# Auto-generated by apmd. Source this file from sh to expose APM\\n";
  script << "# commands (e.g. . \"$(command -v apm-path.sh)\").\\n\n";
  script << "APM_COMMANDS_DIR=\"" << apm::config::getCommandsDir() << "\"\n";
  script << "APM_DEPENDENCIES_DIR=\"" << apm::config::getDependenciesDir()
         << "\"\n";
  script << "APM_SHIM_DIR=\"" << apm::config::APM_BIN_DIR << "\"\n\n";
  script << "APM_TERMUX_ROOT=\"" << apm::config::getTermuxRoot() << "\"\n";
  script << "APM_TERMUX_PREFIX=\"" << apm::config::getTermuxPrefix() << "\"\n";
  script << "APM_TERMUX_INSTALLED_DIR=\"" << apm::config::TERMUX_INSTALLED_DIR
         << "\"\n";
  script << "APM_TERMUX_ENV=\"" << apm::config::TERMUX_ENV_FILE << "\"\n\n";

  script << "apm_path__contains() {\n";
  script << "  case \":$PATH:\" in\n";
  script << "    *:\"$1\":*) return 0 ;;\n";
  script << "  esac\n";
  script << "  return 1\n";
  script << "}\n\n";

  script << "apm_path__add() {\n";
  script << "  dir=\"$1\"\n";
  script << "  if [ -z \"$dir\" ] || [ ! -d \"$dir\" ]; then\n";
  script << "    return 0\n";
  script << "  fi\n";
  script << "  if apm_path__contains \"$dir\"; then\n";
  script << "    return 0\n";
  script << "  fi\n";
  script << "  if [ -z \"$PATH\" ]; then\n";
  script << "    PATH=\"$dir\"\n";
  script << "  else\n";
  script << "    PATH=\"$dir:$PATH\"\n";
  script << "  fi\n";
  script << "  return 0\n";
  script << "}\n\n";

  script << "apm_path__add_pkg_bins() {\n";
  script << "  base=\"$1\"\n";
  script << "  if [ -z \"$base\" ] || [ ! -d \"$base\" ]; then\n";
  script << "    return 0\n";
  script << "  fi\n";
  script << "  for pkg_dir in \"$base\"/*; do\n";
  script << "    if [ ! -d \"$pkg_dir\" ]; then\n";
  script << "      continue\n";
  script << "    fi\n";
  script << "    pkg_name=${pkg_dir##*/}\n";
  script << "    case \"$pkg_name\" in\n";
  script << "      .|..) continue ;;\n";
  script << "    esac\n";
  script << "    apm_path__add \"$pkg_dir/bin\"\n";
  script << "    apm_path__add \"$pkg_dir/usr/bin\"\n";
  script
      << "    apm_path__add \"$pkg_dir/data/data/com.termux/files/usr/bin\"\n";
  script << "  done\n";
  script << "  return 0\n";
  script << "}\n\n";

  script << "apm_path__update() {\n";
  script << "  apm_path__add \"$APM_SHIM_DIR\"\n";
  script << "  apm_path__add \"$APM_COMMANDS_DIR\"\n";
  script << "  apm_path__add \"$APM_DEPENDENCIES_DIR\"\n";
  script << "  [ -f \"$APM_TERMUX_ENV\" ] && . \"$APM_TERMUX_ENV\"\n";
  script << "  apm_path__add \"$APM_TERMUX_ROOT/bin\"\n";
  script << "  apm_path__add \"$APM_TERMUX_PREFIX/bin\"\n";
  script << "  apm_path__add_pkg_bins \"$APM_COMMANDS_DIR\"\n";
  script << "  apm_path__add_pkg_bins \"$APM_DEPENDENCIES_DIR\"\n";
  script << "  export PATH\n";
  script << "}\n\n";

  script << "apm_path__update \"$@\"\n";
  script << "unset -f apm_path__contains\n";
  script << "unset -f apm_path__add\n";
  script << "unset -f apm_path__add_pkg_bins\n";
  script << "unset -f apm_path__update\n";
  script << "unset pkg_dir\n";
  script << "unset pkg_name\n";
  script << "unset base\n";
  script << "unset dir\n";
  script << "unset APM_SHIM_DIR\n";
  script << "unset APM_DEPENDENCIES_DIR\n";
  script << "unset APM_COMMANDS_DIR\n";
  script << "unset APM_TERMUX_ROOT\n";
  script << "unset APM_TERMUX_PREFIX\n";
  script << "unset APM_TERMUX_INSTALLED_DIR\n";
  script << "unset APM_TERMUX_ENV\n";

  return writeExecutableScript(apm::config::COMMANDS_PATH_HELPER, script.str());
}

// Emit the export-path helper that creates/refreshes the global profile file
// and rehashes the current shell as needed.
bool ensureExportScript() {
  std::ostringstream script;
  script << "#!/system/bin/sh\n";
  script << "APM_COMMANDS_DIR=\"" << apm::config::getCommandsDir() << "\"\n";
  script << "APM_SHIM_DIR=\"" << apm::config::APM_BIN_DIR << "\"\n";
  script << "APM_PATH_HELPER=\"" << apm::config::COMMANDS_PATH_HELPER << "\"\n";
  script << "APM_PROFILE_FILE=\"" << apm::config::GLOBAL_PROFILE_FILE << "\"\n";
  script << "APM_PROFILE_MARK=\"" << apm::config::GLOBAL_PROFILE_SOURCED_MARK
         << "\"\n";
  script << "APM_TERMUX_ROOT=\"" << apm::config::getTermuxRoot() << "\"\n";
  script << "APM_TERMUX_PREFIX=\"" << apm::config::getTermuxPrefix() << "\"\n";
  // Keepalive PID location based on runtime root (Android vs emulator)
  script << "APM_KEEPALIVE_PID=\""
         << apm::fs::joinPath(apm::config::getApmRoot(),
                              ".apm_path_keepalive.pid")
         << "\"\n";
  script << "APM_PATH_HOOK_TARGETS=\"/system/etc/profile /system/etc/mkshrc "
            "/etc/profile /data/local/userinit.sh /data/local/tmp/.profile "
            "/data/local/tmp/.mkshrc\"\n";
  script << "APM_SERVICE_HOOK=\"/data/adb/service.d/99apm-path.sh\"\n\n";

  script << "prepare_profile_dir() {\n";
  script << "  profile_dir=$(dirname \"$APM_PROFILE_FILE\")\n";
  script << "  if [ -d \"$profile_dir\" ]; then\n";
  script << "    return 0\n";
  script << "  fi\n";
  script << "  mkdir -p \"$profile_dir\" >/dev/null 2>&1 || return 1\n";
  script << "  return 0\n";
  script << "}\n\n";

  script << "write_profile_file() {\n";
  script << "  prepare_profile_dir || return 1\n";
  script << "  cat > \"$APM_PROFILE_FILE\" <<'APM_PROFILE'\n";
  script << "APM_COMMANDS_DIR=\"" << apm::config::getCommandsDir() << "\"\n";
  script << "APM_SHIM_DIR=\"" << apm::config::APM_BIN_DIR << "\"\n";
  script << "APM_PATH_HELPER=\"" << apm::config::COMMANDS_PATH_HELPER << "\"\n";
  script << "APM_PROFILE_MARK=\"" << apm::config::GLOBAL_PROFILE_SOURCED_MARK
         << "\"\n";
  script << "export ENV=\"" << apm::config::GLOBAL_PROFILE_FILE << "\"\n";
  script << "case \":$PATH:\" in\n";
  script << "  *:\"$APM_SHIM_DIR\":*) ;;\n";
  script << "  *) PATH=\"$APM_SHIM_DIR:$PATH\" ;;\n";
  script << "esac\n";
  script << "case \":$PATH:\" in\n";
  script << "  *:\"$APM_COMMANDS_DIR\":*) ;;\n";
  script << "  *) PATH=\"$APM_COMMANDS_DIR:$PATH\" ;;\n";
  script << "esac\n";
  script << "case \":$PATH:\" in\n";
  script << "  *:\"$APM_TERMUX_ROOT/bin\":*) ;;\n";
  script << "  *) PATH=\"$APM_TERMUX_ROOT/bin:$PATH\" ;;\n";
  script << "esac\n";
  script << "case \":$PATH:\" in\n";
  script << "  *:\"$APM_TERMUX_PREFIX/bin\":*) ;;\n";
  script << "  *) PATH=\"$APM_TERMUX_PREFIX/bin:$PATH\" ;;\n";
  script << "esac\n";
  script << "export PATH\n";
  script << "if [ -f \"$APM_PATH_HELPER\" ]; then\n";
  script << "  . \"$APM_PATH_HELPER\"\n";
  script << "fi\n";
  script << "if [ -n \"$APM_PROFILE_MARK\" ]; then\n";
  script << "  touch \"$APM_PROFILE_MARK\" >/dev/null 2>&1 || true\n";
  script << "fi\n";
  script << "export APM_PROFILE_LOADED=1\n";
  script << "unset APM_COMMANDS_DIR\n";
  script << "unset APM_SHIM_DIR\n";
  script << "unset APM_PATH_HELPER\n";
  script << "unset APM_PROFILE_MARK\n";
  script << "unset APM_TERMUX_ROOT\n";
  script << "unset APM_TERMUX_PREFIX\n";
  script << "APM_PROFILE\n";
  script << "  chmod 0644 \"$APM_PROFILE_FILE\" >/dev/null 2>&1 || true\n";
  script << "  return 0\n";
  script << "}\n\n";

  script << "apm_path__line_exists() {\n";
  script << "  file=\"$1\"\n";
  script << "  needle=\"$2\"\n";
  script
      << "  [ -f \"$file\" ] && /system/bin/grep -F -q \"$needle\" \"$file\" "
         "2>/dev/null\n";
  script << "}\n\n";

  script << "apm_path__append_hook() {\n";
  script << "  file=\"$1\"\n";
  script << "  line=\"$2\"\n";
  script << "  dir=$(dirname \"$file\")\n";
  script << "  mkdir -p \"$dir\" >/dev/null 2>&1 || true\n";
  script << "  [ -f \"$file\" ] || touch \"$file\" >/dev/null 2>&1 || true\n";
  script << "  if apm_path__line_exists \"$file\" \"$line\"; then\n";
  script << "    return 0\n";
  script << "  fi\n";
  script << "  printf \"\\n%s\\n\" \"$line\" >>\"$file\" 2>/dev/null || true\n";
  script << "}\n\n";

  script << "apm_path__install_hooks() {\n";
  script << "  hook=\"[ -f \\\"$APM_PROFILE_FILE\\\" ] && . "
            "\\\"$APM_PROFILE_FILE\\\"\"\n";
  script << "  for target in $APM_PATH_HOOK_TARGETS; do\n";
  script << "    apm_path__append_hook \"$target\" \"$hook\"\n";
  script << "  done\n";
  script << "  if [ -d \"/data/adb/service.d\" ]; then\n";
  script << "    if ! apm_path__line_exists \"$APM_SERVICE_HOOK\" \"$hook\"; "
            "then\n";
  script << "      printf '#!/system/bin/sh\\n%s\\n' \"$hook\" "
            ">\"$APM_SERVICE_HOOK\" 2>/dev/null || true\n";
  script << "      chmod 0755 \"$APM_SERVICE_HOOK\" >/dev/null 2>&1 || true\n";
  script << "    fi\n";
  script << "  fi\n";
  script << "}\n\n";

  script << "apm_path__start_keepalive() {\n";
  script << "  pid_file=\"$APM_KEEPALIVE_PID\"\n";
  script << "  if [ -f \"$pid_file\" ]; then\n";
  script << "    old_pid=$(cat \"$pid_file\" 2>/dev/null || true)\n";
  script << "    case \"$old_pid\" in\n";
  script << "      ''|*[!0-9]*) old_pid='' ;;\n";
  script << "    esac\n";
  script << "    if [ -n \"$old_pid\" ] && kill -0 \"$old_pid\" 2>/dev/null; "
            "then\n";
  script << "      return 0\n";
  script << "    fi\n";
  script << "  fi\n";
  script << "  mkdir -p \"$(dirname \"$pid_file\")\" >/dev/null 2>&1 || true\n";
  script << "  ( while :; do\n";
  script << "      apm_path__install_hooks\n";
  script << "      [ -f \"$APM_PATH_HELPER\" ] && . \"$APM_PATH_HELPER\" "
            ">/dev/null 2>&1\n";
  script << "      sleep 5\n";
  script << "    done ) >/dev/null 2>&1 &\n";
  script << "  echo $! > \"$pid_file\" 2>/dev/null || true\n";
  script << "}\n\n";

  script << "refresh_shell_now() {\n";
  script << "  if [ -f \"$APM_PROFILE_FILE\" ]; then\n";
  script << "    . \"$APM_PROFILE_FILE\" >/dev/null 2>&1\n";
  script << "  elif [ -f \"$APM_PATH_HELPER\" ]; then\n";
  script << "    . \"$APM_PATH_HELPER\" >/dev/null 2>&1\n";
  script << "  fi\n";
  script << "  hash -r 2>/dev/null || true\n";
  script << "}\n\n";

  script << "write_profile_file\n";
  script << "apm_path__install_hooks\n";
  script << "refresh_shell_now\n";
  script << "apm_path__start_keepalive\n";

  return writeExecutableScript(apm::config::COMMANDS_EXPORT_SCRIPT,
                               script.str());
}

// Fork/exec /system/bin/sh with the generated script to apply PATH updates.
bool runScript(const std::string &path) {
  pid_t pid = ::fork();
  if (pid < 0) {
    apm::logger::warn("export_path: fork failed for " + path + ": " +
                      std::strerror(errno));
    return false;
  }

  if (pid == 0) {
    ::execl("/system/bin/sh", "sh", path.c_str(), (char *)nullptr);
    _exit(127);
  }

  int status = 0;
  if (::waitpid(pid, &status, 0) < 0) {
    apm::logger::warn("export_path: waitpid failed for " + path + ": " +
                      std::strerror(errno));
    return false;
  }

  if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
    apm::logger::warn("export_path: script " + path + " exited with error");
    return false;
  }

  return true;
}

// Source the global profile file inside a child shell so that ENV-based shells
// pick up APM_PATH_HELPER on next launch.
static bool sourceProfileFile() {
  const std::string profile = apm::config::GLOBAL_PROFILE_FILE;
  if (!apm::fs::pathExists(profile)) {
    apm::logger::warn("export_path: profile file not found at " + profile);
    return false;
  }

  std::string cmd = ". \"" + profile + "\"";
  pid_t pid = ::fork();
  if (pid < 0) {
    apm::logger::warn("export_path: fork failed while sourcing profile: " +
                      std::string(std::strerror(errno)));
    return false;
  }

  if (pid == 0) {
    ::execl("/system/bin/sh", "sh", "-c", cmd.c_str(), (char *)nullptr);
    _exit(127);
  }

  int status = 0;
  if (::waitpid(pid, &status, 0) < 0) {
    apm::logger::warn("export_path: waitpid failed for profile source: " +
                      std::string(std::strerror(errno)));
    return false;
  }

  if (!WIFEXITED(status) || WEXITSTATUS(status) != 0) {
    apm::logger::warn("export_path: sourcing profile exited with error status");
    return false;
  }

  return true;
}

} // namespace

namespace apm::daemon::path {

// Ensure helper scripts exist, run the export script immediately, and source
// the profile marker during the same invocation so new commands are usable at
// once.
void refreshPathEnvironment() {
  // On emulator mode, skip Android shell integration and instead generate a
  // simple env file for the host shell.
  if (apm::config::isEmulatorMode()) {
    generateEmulatorEnv();
    return;
  }

  if (!ensureCommandsPathHelperScript()) {
    return;
  }

  if (!ensureExportScript()) {
    return;
  }

  if (!runScript(apm::config::COMMANDS_EXPORT_SCRIPT)) {
    return;
  }

  sourceProfileFile();
}

// Guarantee that at least one shell has sourced the generated profile file so
// that future shells inherit PATH updates through ENV.
void ensureProfileLoaded() {
  if (apm::config::isEmulatorMode()) {
    // Nothing to do on the host; users can `source` the generated env file.
    return;
  }
  // Always try to (re)source the profile so PATH stays current after installs.
  if (!apm::fs::pathExists(apm::config::GLOBAL_PROFILE_FILE)) {
    refreshPathEnvironment();
    return;
  }

  if (!sourceProfileFile()) {
    apm::logger::warn("export_path: failed to source global profile");
  }
}

// Generate apm-env.sh for emulator mode with atomic write
void generateEmulatorEnv() {
  if (!apm::config::isEmulatorMode()) {
    return; // Only for emulator mode
  }

  std::string envPath = apm::config::getApmRoot() + "/apm-env.sh";
  std::string tmpPath = envPath + ".tmp";

  // Collect all command directories
  std::vector<std::string> pathDirs;

  // Add main commands directory
  std::string commandsDir = apm::config::getCommandsDir();
  if (apm::fs::isDirectory(commandsDir)) {
    auto entries = apm::fs::listDir(commandsDir, false);
    for (const auto &entry : entries) {
      std::string pkgDir = apm::fs::joinPath(commandsDir, entry);
      if (apm::fs::isDirectory(pkgDir)) {
        // Check for bin subdirectory
        std::string binDir = apm::fs::joinPath(pkgDir, "bin");
        if (apm::fs::isDirectory(binDir)) {
          pathDirs.push_back(binDir);
        }
        // Also add package directory itself
        pathDirs.push_back(pkgDir);
      }
    }
  }

  // Add dependencies directory
  std::string depsDir = apm::config::getDependenciesDir();
  if (apm::fs::isDirectory(depsDir)) {
    auto entries = apm::fs::listDir(depsDir, false);
    for (const auto &entry : entries) {
      std::string depDir = apm::fs::joinPath(depsDir, entry);
      if (apm::fs::isDirectory(depDir)) {
        std::string binDir = apm::fs::joinPath(depDir, "bin");
        if (apm::fs::isDirectory(binDir)) {
          pathDirs.push_back(binDir);
        }
        pathDirs.push_back(depDir);
      }
    }
  }

  // Write to temporary file
  std::ofstream out(tmpPath);
  if (!out.is_open()) {
    apm::logger::warn("export_path: failed to create " + tmpPath);
    return;
  }

  // Write header with timestamp
  auto now = std::time(nullptr);
  char timeStr[100];
  std::strftime(timeStr, sizeof(timeStr), "%Y-%m-%d %H:%M:%S",
                std::localtime(&now));

  out << "#!/bin/bash\n";
  out << "# APM Emulator Mode Environment\n";
  out << "# Generated: " << timeStr << "\n";
  out << "# Source this file to make installed commands available:\n";
  out << "#   source " << envPath << "\n";
  out << "\n";

  if (pathDirs.empty()) {
    out << "# No packages installed yet\n";
  } else {
    out << "# Add APM package directories to PATH\n";
    for (const auto &dir : pathDirs) {
      out << "export PATH=\"" << dir << ":$PATH\"\n";
    }
  }

  out.close();

  // Atomic rename
  if (::rename(tmpPath.c_str(), envPath.c_str()) != 0) {
    apm::logger::warn("export_path: failed to rename " + tmpPath + " to " +
                      envPath);
    ::unlink(tmpPath.c_str());
    return;
  }

  // Make it executable
  ::chmod(envPath.c_str(), 0755);

  std::cout << "\nTo use installed commands in your shell, run:\n";
  std::cout << "  source " << envPath << "\n";
}

} // namespace apm::daemon::path
