#!/sbin/sh
#
# APM - Android Package Manager
#
# RedHead Industries - Technologies Branch
# Copyright (C) 2025 RedHead Industries
#
# File: addond_head
# Purpose: Enumerate files to back up/restore for APM across OTAs (addon.d hook).
# Last Modified: December 4th, 2025. - 09:07 AM Eastern Time
# Author: Matthew DaLuz - RedHead Founder
#
# APM is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# APM is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with APM. If not, see <https://www.gnu.org/licenses/>.
#
#
# ADDOND_VERSION=3
#
# /system/addon.d/30-apm.sh
# Backup and restore APM system-wide installation across OTA updates
#
. /tmp/backuptool.functions

list_files() {
cat <<EOF
bin/apm
bin/apmd
bin/amsd
etc/init/init.apmd.rc
etc/init/init.amsd.rc
etc/selinux/apm.cil
etc/selinux/apm_file_contexts
etc/selinux/apm_property_contexts
etc/selinux/apm_service_contexts
